type: code
max_score: 15
code:
  - .laborantum/texts/Homeworks/5. Gauss Algorithm/2. Gauss Elimination Step 2/task.ipynb
  - code/gauss_elimination_2.py
run_test:
  - ipython .laborantum/utils/python_struct_checker.py -- 