type: code
max_score: 1
code:
  - .laborantum/texts/Homeworks/3. Matrices/12. Einstein's Rule/task.ipynb
run_test:
  - ipython .laborantum/utils/python_struct_checker.py -- -t ".laborantum/texts/Homeworks/3. Matrices/12. Einstein's Rule"