type: code
max_score: 1
code: 
  - .laborantum/texts/Homeworks/1. Vectors/17. Elementwise Arithmetics Exercise/task.py
run_test: 
  - >
    python .laborantum/utils/python_struct_checker.py 
    -t ".laborantum/texts/Homeworks/1. Vectors/17. Elementwise Arithmetics Exercise/"
report_path:
  .laborantum/reports/Homeworks/1. Vectors/17. Elementwise Arithmetics Exercise/report.json
