type: code
max_score: 1
code: 
  - .laborantum/texts/Homeworks/2. Vector Spaces/6. Linear Independency Task/task.ipynb
run_test: 
  - >
    ipython .laborantum/utils/python_struct_checker.py --
    -t ".laborantum/texts/Homeworks/2. Vector Spaces/6. Linear Independency Task/"
report_path:
  .laborantum/reports/Homeworks/2. Vector Spaces/6. Linear Independency Task/report.json