type: code
max_score: 1
code: 
  - .laborantum/texts/Homeworks/2. Vector Spaces/12. Covariant Coordinates Numpy I/task.ipynb
run_test: 
  - >
    ipython .laborantum/utils/python_struct_checker.py --
    -t ".laborantum/texts/Homeworks/2. Vector Spaces/12. Covariant Coordinates Numpy I/"
report_path:
  .laborantum/reports/Homeworks/2. Vector Spaces/12. Covariant Coordinates Numpy I/report.json