type: code
max_score: 1
code: 
  - .laborantum/texts/Homeworks/1. Vectors/26. Cosine Distance Numpy/task.ipynb
run_test: 
  - >
    ipython .laborantum/utils/python_struct_checker.py --
    -t ".laborantum/texts/Homeworks/1. Vectors/26. Cosine Distance Numpy/"
report_path:
  .laborantum/reports/Homeworks/1. Vectors/26. Cosine Distance Numpy/report.json