type: code
max_score: 5
code:
  - .laborantum/texts/Homeworks/6. Nonsquare SLE/2. Matrix Null-Space/task.ipynb
  - code/find_kernel.py
run_test:
  - ipython .laborantum/utils/python_struct_checker.py --