type: code
max_score: 1
code: 
  - .laborantum/texts/Homeworks/1. Vectors/10. Sum of Vectors/task.ipynb
run_test: 
  - >
    ipython .laborantum/utils/python_struct_checker.py --
    -t ".laborantum/texts/Homeworks/1. Vectors/10. Sum of Vectors/"
report_path:
  .laborantum/reports/Homeworks/1. Vectors/10. Sum of Vectors/report.json