type: code
max_score: 1
code: 
  - .laborantum/texts/Homeworks/2. Vector Spaces/8. Contra- and Co- Variant Coordiantes Task/task.py
run_test: 
  - >
    ipython .laborantum/utils/python_struct_checker.py --
    -t ".laborantum/texts/Homeworks/2. Vector Spaces/8. Contra- and Co- Variant Coordiantes Task/"
report_path:
  .laborantum/reports/Homeworks/2. Vector Spaces/8. Contra- and Co- Variant Coordiantes Task/report.json