order:
  - 1. Matrices Quiz
  - 2. Matrix Arithmetics
  - 3. Matrix Transposition
  - 4. Matrix Product
  - 5. Matrix-Vector Product
  - 6. Matrix Dot-Product Numpy
  - 7. Matrix Product Quiz II
  - 8. Matrix Product
  - 9. Matrix Product II
  - 10. Triangular Matrices Product
  - 11. Numpy Matrix Expression
  - 12. Einstein's Rule
  - 13. LL product
  - 14. Diagonal Matrices Product
  - 15. Sparse Matrix Product
