type: code
max_score: 1
code: 
  - .laborantum/texts/Homeworks/2. Vector Spaces/9. Contravariant Coordinates Numpy/task.ipynb
run_test: 
  - >
    ipython .laborantum/utils/python_struct_checker.py --
    -t ".laborantum/texts/Homeworks/2. Vector Spaces/9. Contravariant Coordinates Numpy/"
report_path:
  .laborantum/reports/Homeworks/2. Vector Spaces/9. Contravariant Coordinates Numpy/report.json