type: code
max_score: 5
code:
  - .laborantum/texts/Homeworks/5. Gauss Algorithm/5. PLU Decomposition/task.ipynb
  - code/plu_decomposition.py
run_test:
  - ipython .laborantum/utils/python_struct_checker.py --
