order:
  - 1. Vectors as Arrows
  - 2. Vectors as Sets of Coordinates
  - 3. Vectors in Numpy Task
  - 4. Length of Vector Cards
  - 5. Length of Vector Task
  - 6. Length of Vector Numpy
  - 7. Length Numpy
  - 8. Direction of Vector
  - 9. Direction of Vector Numpy
  - 10. Sum of Vectors
  - 11. Sum of Vectors Quiz
  - 12. Sum of Vectors Quiz 2
  - 13. Sum of Vectors Numpy Vectorized
  - 14. Scaling Quiz
  - 17. Elementwise Arithmetics Exercise
  - 19. Scalar Product Quiz
  - 21. Scalar Product 2D Cards
  - 22. Scalar Product ND Cards
  - 23. Geometric Meaning Exercise
  - 25. Geometric Meaning Quiz
  - 26. Cosine Distance Numpy
  - 27. Projection Exercise
  - 29. Orthonormalisation Quiz
  - 30. Orthonormalisation Numpy
  - 31. Exercise Vectors 1
  - 32. Exercise Vectors 2
  - 33. Exercise Vectors 3
