
  type: choose_any
  header: 'Matrix Product'
  shuffle: true
  grade_all: true
  max_score: 1
  quiz:
    variants:
    - text: |
        $\forall A \in \mathbb R^{N \times N}$ and 
        $\forall \mathbf x \in \mathbb R^M \Rightarrow 
        A \mathbf x \in \mathbb R^N$ 
      is_correct: false
    - text: |
        $\forall A \in \mathbb R^{N \times N}$ and 
        $\forall \mathbf x \in \mathbb R^N \Rightarrow 
        A \mathbf x \in \mathbb R^N$ 
      is_correct: true
    - text: |
        $\forall A \in \mathbb R^{N \times K}$ and 
        $\forall B \in \mathbb R^{K \times M} \Rightarrow 
        A B \in \mathbb R^{N \times M}$ 
      is_correct: true
    - text: |
        $\forall A \in \mathbb R^{N \times N}$ and 
        $\forall B \in \mathbb R^{K \times M} \Rightarrow 
        A B \in \mathbb R^{N \times M}$ 
      is_correct: false
    - text: |
        $\forall A = \begin{bmatrix}
          \mathbf a_1 & 
          \dots &
          \mathbf a_N
        \end{bmatrix} \in \mathbb R^{K \times N}$ and
        $\forall B = \begin{bmatrix}
          \mathbf b_1 & \dots & \mathbf b_M
        \end{bmatrix} \in \mathbb R^{K \times M} \Rightarrow$
        $A^T B = \begin{bmatrix}
          \left<\mathbf a_1, \mathbf b_1\right> & \dots & \left<\mathbf a_1, \mathbf b_M\right> \\
          \vdots & \ddots & \vdots \\
          \left<\mathbf a_N, \mathbf b_1\right> & \dots & \left<\mathbf a_N, \mathbf b_M\right>
        \end{bmatrix} \in \mathbb R^{N \times M}$
      is_correct: true
    - text: |
        $\forall A \in \mathbb R^{K \times N}$ and
        $\forall B = \begin{bmatrix}
          \mathbf b_1 & \dots & \mathbf b_M
        \end{bmatrix} \in \mathbb R^{K \times M} \Rightarrow$
        $A^T B = \begin{bmatrix}
          A^T \mathbf b_1 & \dots & A^T \mathbf b_M
        \end{bmatrix} \in \mathbb R^{N \times M}$
      is_correct: true
    - text: |
        $\forall B \in \mathbb R^{K \times N}$ and
        $\forall A = \begin{bmatrix}
          \mathbf a_1 & \dots & \mathbf a_N
        \end{bmatrix} \in \mathbb R^{K \times M} \Rightarrow$
        $A^T B = \begin{bmatrix}
          \mathbf a_1^T B \\ \vdots \\ \mathbf a_N^T B
        \end{bmatrix} \in \mathbb R^{N \times M}$
      is_correct: true
    - text: |
        Suppose that we want to calculate the product $A B$ and we realise
        that matrix $A$ contains zeros in $50\%$ of the positions. That
        means that we can perform $50\%$ less operations of multiplication to
        calculate $AB$
      is_correct: true
    - text: |
        Suppose that we want to calculate the product $A B$ and we realise
        that both matrices $A$ and $B$ contains zeros in $50\%$ of the 
        positions. That
        means that we can perform $75\%$ less operations of multiplication to
        calculate $AB$
      is_correct: false
    - text: |
        Matrix product $AB$ is always equal to elementwise matrix
        product $A \cdot B$
      is_correct: false
    - text: |
        $\forall \alpha, \beta \in \mathbb R$, $\forall \mathbf x \in \mathbb R^M$ and 
        $\forall A, B \in \mathbb R^{N \times M} \Rightarrow$
        $(\alpha A + \beta B) \mathbf x = \alpha A \mathbf x + \beta B \mathbf x$
      is_correct: true
    - text: |
        $\forall \alpha, \beta \in \mathbb R$, 
        $\forall \mathbf x, \mathbf y \in \mathbb R^M$ and 
        $\forall A \in \mathbb R^{N \times M} \Rightarrow$
        $A (\alpha \mathbf x + \beta \mathbf y)  = \alpha A \mathbf x + \beta A \mathbf y$
      is_correct: true

    
